### ISSUE TITLE
pages always come up, in dutch?

### ISSUE THREAD

**Issue by seanwatkins** [waschinski/photo-stream#20]
Just got photo-stream going .. and I've noticed even on other examples, Chrome is wanting to translate from Dutch to English. Any idea why? I searched all around I can't see why-

**Comment by waschinski** [comment]
That's really a strange behaviour. If it would be only your specific photo-stream page I'd assume it could be the name of one of the images being used making Chrome think it's Dutch.

While I don't encounter this on any of the examples (on Edge) though maybe the translation feature can be disabled via some HTML. I will look into that as It's not really a helpful feature for photo-stream anyway.

**Comment by boerniee** [comment]
Hello @seanwatkins 
I have committed a fix for that annoying chrome translation popup. It supressed the popup in my local dev environment and also on my instance of photo-stream.
This will be included in the next release and maybe you can test, if this also works for you. :)
If it doesnt work, please reopen this issue.
