### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by maddingamer** [waschinski/photo-stream#36]
Hi, thanks for your work!
Is it possible to protect the stream via password without just using basic auth? 
Thanks!

**Comment by waschinski** [comment]
Hi Martin, not right now, but I think @boerniee did this on an installation of photo-stream, not sure how though. Maybe he can chime in on this topic.

**Comment by boerniee** [comment]
Hello 🙂

I did it with basic auth via htaccess. Sorry 🤷‍♂️
But if you are using docker and a reverse proxy, maybe you can use Authalia or something similar.

**Comment by oliverhihn** [comment]
Maybe "Keycloak" is an option.

**Comment by maddingamer** [comment]
Thanks for your suggestions :)
