### ISSUE TITLE
Difficult to zoom in and navigate on mobile devices

### ISSUE THREAD

**Issue by ckuethe** [waschinski/photo-stream#44]
So I'm using photostream to host a little gallery of my astrophotography; its difficult to zoom into an image on mobile devices because any touch on the screen causes a transition to the previous photo, the next photo, or the gallery view. Is there a way to make the... button areas... be maybe 10%  of the window size so that one can easily pan/zoom on mobile?

**Comment by waschinski** [comment]
Thanks for bringing this up. I know this issue has been first, but let's use #50 to cover this please. Feel free to discuss ideas on the UI side with the other people.
