### ISSUE TITLE
github/instagram buttons

### ISSUE THREAD

**Issue by amenolo** [waschinski/photo-stream#46]
- no option to disable instagram button
- SHOW_OFFICIAL_GITHUB refers to waschinski github button only so no option to disable github button too

![immagine](https://user-images.githubusercontent.com/29974944/194746644-7428ea60-d35f-46bb-9882-c3d959a0c6ac.png)

![immagine](https://user-images.githubusercontent.com/29974944/194746703-fe8b80ae-2c0c-4c14-8fcf-33e29e1cdfa2.png)

BTW I noticed that the original github/instagram buttons are used when declaring GITHUB_USERNAME/INSTAGRAM_USERNAME...I'm not a code-guy but I wonder if the aforementioned issues maybe depend on this...

![immagine](https://user-images.githubusercontent.com/29974944/194748856-887e91f3-0d82-4949-b06d-803aee6fb0ef.png)
![immagine](https://user-images.githubusercontent.com/29974944/194748875-fe86fab6-3384-48d9-8b38-ea6558873e80.png)

Thanks!

**Comment by waschinski** [comment]
This actually looks like an issue with your environment variables. How did you set up Photo Stream?
