### ISSUE TITLE
wrong order on render

### ISSUE THREAD

**Issue by ElFishi** [waschinski/photo-stream#51]
I followed [the readme](https://github.com/waschinski/photo-stream#on-render) and built a static site on render. 
It all worked nice and dandy, however the resulting order of photos seems wrong. 
In the default setting photo-stream shows the photos first that have been submitted to github first. 
Switching the default order via DEFAULT_REVERSE_SORT is not quite an option for me as I want to both host a number of exisiting photos and then append new ones from day to day. 
As it stands I can't get the photos to be shown in the right order: the oldest photo of the old series is always shown next to the latest photo commited. 
I appreciate that github does not know the date the photo was created, but can photo-stream pick up the time the photo was committed?

**Comment by waschinski** [comment]
Photo Stream does use the following date data when sorting: Exif data (date_time_original) or file modification date.
So my guess is your photos do not have Exif data and so are being sorted by the date they got added to GitHub.

**Comment by ElFishi** [comment]
Thanks for pointing this out. My legacy fotos are an instagram dump w/o exif data. I now faked a DateTimeOriginal to fix the order of the set and deployed again, and, alas, it worked!

**Comment by waschinski** [comment]
Great to hear it's now working now! Maybe we should start adding a FAQ/Notes section in the README? :D
