### ISSUE TITLE
Feature request: Authentication

### ISSUE THREAD

**Issue by ElFishi** [waschinski/photo-stream#52]
Is there a way the resulting site could require authentication before the stream is shown? 
Thx.

**Comment by oliverhihn** [comment]
You cloud put it behind an nginx reverse proxy and use the basic auth. functionality of nginx. That would be an easiest way to accomplish that.

**Comment by dumblob** [comment]
Related: https://github.com/waschinski/photo-stream/issues/29#issuecomment-1281129954

**Comment by ElFishi** [comment]
Thanks for responding. 
I was actually hoping to use some authentification when hosting a static site on render.

**Comment by oliverhihn** [comment]
Then you could maybe use https://github.com/oauth2-proxy/oauth2-proxy

**Comment by ElFishi** [comment]
Thanks for pointing me this way. It turns out render has a [page on OAuth](https://render.com/blog/password-protect-with-oauth2-proxy). 
And it also has a [page on PageCrypt](https://render.com/blog/static-site-auth-pagecrypt) which is quite OK for my purpose.

**Comment by waschinski** [comment]
Thanks @oliverhihn for chiming in here and helping out, it's much appreciated.

Also, PageCrypt looks interesting and like something that would be nice to have included in Photo Stream out of the box while keeping it rather simple.

**Comment by ElFishi** [comment]
I pretty much followed their [example](https://github.com/render-examples/pagecrypt). 
On render I use the Build Command `bundle exec jekyll build && yarn && yarn run build` and the package.json goes 
```
{
  "scripts": {
    "build": "pagecrypt _site/index.html _site/index.htm $PASSWORD && rm _site/index.html"
  },
  "engines": {
    "node": ">=16 <19"
  },
  "devDependencies": {
    "pagecrypt": "^5.4.0"
  }
}
```
Mind the version restriction on node, b/c [node v19 throws an error](https://github.com/render-examples/pagecrypt/issues/1#issue-1418916337).
