### ISSUE TITLE
What is the photo directory?

### ISSUE THREAD

**Issue by xiNeRoar** [waschinski/photo-stream#56]
I am using docker to install and mount my image folder e.g. "picture" to /photos/original but there is no photo showing up. What have I done wrong?
![image](https://user-images.githubusercontent.com/66216186/203972998-5414ec17-f613-44e3-bafc-dcb457125319.png)

**Comment by waschinski** [comment]
![image](https://user-images.githubusercontent.com/25221082/209653969-84394121-d1fa-4ec3-b37d-50556361f69e.png)
Sorry for the late reply. This is how it looks on my side. In my local folder `docker/photo-stream` there's a subfolder `original` containing the photos, make sure the mount path is correct, it should be `/photo-stream/photos/` and must also include an `original` folder.
