### ISSUE TITLE
Trailing slash breaks URL in RSS feed

### ISSUE THREAD

**Issue by nicosomb** [waschinski/photo-stream#61]
Thank you for photo-stream! 

In the `.env` file, I put `https://mywebsite.com/` for the `URL` setting, but in the generated RSS feed, I have `<media:thumbnail xmlns:media="http://search.yahoo.com/mrss/" url="https://mywebsite.com//photos/large/IMG_2809-686656.jpeg" />` with 2 slashes. 

It should be removed but I don't see how I can fix it quickly.

**Comment by boerniee** [comment]
Hi,
thank you for your issue. I will have a look at this. We should handle the site url programmatically so we dont have to rely on the trailing slash in the configuration.

**Comment by waschinski** [comment]
This will be a breaking change in the next release.
