### ISSUE TITLE
WebP support? 

### ISSUE THREAD

**Issue by nicosomb** [waschinski/photo-stream#68]
Hello, 

Is that possible to add WebP support to your great tool?

**Comment by waschinski** [comment]
While technically the library in use (libvips) can handle WebP and a variety of other formats, the project is pretty much hard-coded to only work with jpeg.

I would need to take a deeper look but files like `photo_filter.rb`, `rename_photos.rb` etc would need to implement code depending on the image format by the file's extension.

**Comment by waschinski** [comment]
Good news, months ago I already played around with replacing Exifr with Exiftools which supports more than jpeg and tiff files. I dropped a WebP file in the `dev` tree and it worked right away. :) Going to prepare a merge after some more testing.

**Comment by nicosomb** [comment]
@waschinski website building seems to be longer than before. But it works se well 🎉

**Comment by waschinski** [comment]
> @waschinski website building seems to be longer than before. But it works se well 🎉

Thanks for the feedback, great to hear it works well so far. :)

I have seen some rendering issues on the [demo page](https://photo-stream-muh3.onrender.com) but nothing I can reproduce consistently on that remote side nor locally. If you happen to come across something strange please let me know.

**Comment by waschinski** [comment]
That's a pretty huge increase. My guess is that `exifr` was a lot faster than `exiftool` but I would need to get some confirmation on that.

**Comment by waschinski** [comment]
The `exiftool` website is mentioning [performance](https://exiftool.org/#performance) and ways to improve it. I will try looking into options provided by the [exiftool.rb](https://github.com/exiftool-rb/exiftool.rb.
