### ISSUE TITLE
Docker error and questions

### ISSUE THREAD

**Issue by salicius** [waschinski/photo-stream#72]
Hi, I'm starting right now with docker so please forgive my ignorance. I have some questions:

1) I trying to start this docker image so with the terminal I used this commands:
<img width="1206" alt="Screenshot 2023-03-17 at 12 22 13 PM" src="https://user-images.githubusercontent.com/78569177/225897629-c2544b73-643c-4783-9bb0-02cd481427b4.png">but then if I open my browser at localhost:8080 it shows nothing. Where am I going wrong?

2) To edit images files do I have to go to Docker Desktop -> Containers -> My Container -> Files and here create a folder named "original" ?

3) Without docker if I fork the repo and clone it locally with vscode how can I run it in my localhost ?

**Comment by waschinski** [comment]
Hi, thanks for checking out Photo Stream.

1. You should map port 4000 like `-p 4000:4000` and then open `localhost:4000` in your browser on the same PC.
2. With Docker you should look into volume mounts e.g. `-v /your/local/folder/:/photo-stream/photos`. Make sure there's a folder called `original` inside your local folder which contains the photos.
3. When cloned (you don't need to fork just for checking it out) just run this command: `bundle exec jekyll serve`

**Comment by salicius** [comment]
> Hi, thanks for checking out Photo Stream.
> 
> 1. You should map port 4000 like `-p 4000:4000` and then open `localhost:4000` in your browser on the same PC.
> 2. With Docker you should look into volume mounts e.g. `-v /your/local/folder/:/photo-stream/photos`. Make sure there's a folder called `original` inside your local folder which contains the photos.
> 3. When cloned (you don't need to fork just for checking it out) just run this command: `bundle exec jekyll serve`

Ok thank you, I added the folder "original" following the path I described in my point no. 2 (sorry I don't get how to "look into volume mounts" how you said):

<img width="1280" alt="Screenshot 2023-03-17 at 5 44 15 PM" src="https://user-images.githubusercontent.com/78569177/225967565-33799f82-417f-4465-b2f4-20b97689e4ad.png">


but localhost shows all images with the broken thumbnail:

<img width="1280" alt="Screenshot 2023-03-17 at 5 41 49 PM" src="https://user-images.githubusercontent.com/78569177/225966474-daff1dea-b8b0-4bae-9e79-c5e40f4c9b12.png">

**Comment by waschinski** [comment]
I actually didn't know Docker Desktop allows to add files/folders like that. Anyway, your photos need to end up at `/photo-stream/photos/original/` in your container.

I strongly advise you to read more about the `docker run` command though, especially about [volumes](https://docs.docker.com/engine/reference/commandline/run/#volume).

**Comment by salicius** [comment]
Ok thanks, I'm trying to figure out how to access the volume to change the files inside it but it seems that on macOS Docker does not allow this directly (https://stackoverflow.com/questions/54886883/where-docker-volumes-are-located) and currently I can only do it through Docker Desktop.

**Comment by waschinski** [comment]
You don't need to use a volume, you can also mount an existing folder like that `-v /Users/yourname/Desktop/photo-stream-photos/:/photo-stream/photos` when starting the container.

**Comment by salicius** [comment]
Ok got it, thanks a lot!
