### ISSUE TITLE
How to use to generate a static site?

### ISSUE THREAD

**Issue by engeir** [waschinski/photo-stream#78]
I have been using this for a while and been very happy about the simplicity of the website. However, every time I have wanted to upload new photos I've had a hard time getting it to work. (My [repo](https://github.com/engeir/photo-stream) and [website](https://gallery.flottflyt.com/).)

## Following docker

When trying to follow the docker approach, this is how I understand it should be done:

```console
# Install the project
$ docker pull waschinski/photo-stream:latest
# and it seems to me that there are no further instructions?
```

The other alternative as I understand it would be:

```console
# Install the project
$ docker-compose up -d
# and it seems to me that there are no further instructions?
```

Then there is the `docker-compose build` command mentioned in the section about raspberry-pi, so it seems like this is not relevant unless one is using a raspberry-pi?

## Manually

Installing from a release:

```console
# In this case I cloned the repo
$ git clone https://github.com/waschinski/photo-stream.git
# Since I'm on MacOS I then run
$ xcode-select --install
$ ruby -v
ruby 3.1.2p20 (2022-04-22 revision 4491bb740a) [x86_64-darwin21]
$ gem install bundler jekyll
$ bundle install
$ bundle exec jekyll build
```

But the above results in an error also mentioned in #77.

All approaches mentioned in the README are a bit confusing to me, so it would be very helpful to have a "step-by-step preferred installation and usage" laid out.

**Comment by waschinski** [comment]
Hi, it actually depends a bit on how you want to use photo-stream. It looks like you want to use it via docke, so there usually is no need to fork the project to begin with.
Basically it should be as follows:

1. Modify the `.env` file according to your needs. Make sure that `PHOTO_PATH` is set correctly or no photos will be shown.
2. Create and start the container via `docker compose up -d`.
3. Access photo-stream via `http://localhost:4000`.

Then every time you add or delete photos in the folder defined in `PHOTO_PATH` the site should be rebuild automatically.

**Comment by engeir** [comment]
Okay, thanks, got it!
