### ISSUE TITLE
Numeric-only image names break the arrow key JS.

### ISSUE THREAD

**Issue by danbush** [waschinski/photo-stream#8]
I'm pretty sure this is probably just a situation where something should be explicitly made a string, but I hadn't found where that should go because it was just easier for me to rename my files.

**Comment by waschinski** [comment]
Thanks for reporting this. Numeric IDs were indeed causing problems with the CSS selector so I simply added a prefix (`id-`) to the IDs to basically force them to be a string.

**Comment by danbush** [comment]
perfect, thats basically what I did as a temp fix but in reverse. thank you!
