### ISSUE TITLE
docker-compose does not work

### ISSUE THREAD

**Issue by ribtoks** [waschinski/photo-stream#85]
I downloaded `docker-compose.yml` file, added `.env` file with my overrides, run `docker-compose up`, it took quite some time to generate something (wait for it), and then the webiste at `0.0.0.0:4000` did not have any preview whatsoever. Lots of errors in container logs like `[2023-09-08 11:54:17] ERROR `/photos/thumbnail/5DM36976_4_-ccf4df.jpg' not found.` Directory `/photos/thumbnails` is absent too. How to use this?

Ubuntu 22.04 with latest docker. I tried tag `latest` as well as `dev` with the same success.

UPD. This issue is similar to #72 but the difference is that I'm quite sure I mounted directory correctly. At least I can see entirety of my files in the container's `photos/originals` as well as `_site/photos/originals`

**Comment by waschinski** [comment]
Hey, have you tried running it without any changes and without mounting your own photos? The site should be able to be generated and served this way.

**Comment by ribtoks** [comment]
Hi. After this repository did not work (and also instructions are unclear), I found Gallery Deluxe for Hugo (I use Hugo for my other websites anyways, as Jekyll was and is super slow). So I sort of don't need `docker-compose.yml` to work anymore. No hard feelings and all the best with the project!
