### ISSUE TITLE
No such file or directory @ rb_sysopen - photos/original/DSC03516.JPG in feed.xml

### ISSUE THREAD

**Issue by jessecrouch** [waschinski/photo-stream#9]
Trying to build using manual instructions. Running on Ruby 2.7.0p
Added photos/originals, added single photo to directory. Then:

/photo-stream git:(master) ✗ bundle exec jekyll build                  [21/08/23|14:22:01]
Configuration file: /home/jesse/docs/clients/photography/photo-stream/_config.yml
            Source: /home/jesse/docs/clients/photography/photo-stream
       Destination: /home/jesse/docs/clients/photography/photo-stream/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: No such file or directory @ rb_sysopen - photos/original/DSC03516.JPG in feed.xml
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `build` command
                     for any additional information or backtrace.
                    ------------------------------------------------
Traceback (most recent call last):
        55: from /usr/local/bin/jekyll:23:in `<main>'
        54: from /usr/local/bin/jekyll:23:in `load'
        53: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
        52: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        51: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        50: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        49: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        48: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        47: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        46: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        45: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
        44: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        43: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
        42: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
        41: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
        40: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
        39: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:211:in `render'
        38: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `render_pages'
        37: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `each'
        36: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:539:in `block in render_pages'
        35: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'
        34: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'
        33: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:80:in `render_document'
        32: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:131:in `render_liquid'
        31: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        30: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        29: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        28: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        27: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        26: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        25: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        24: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        23: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        22: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        21: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        20: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
        19: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        18: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:79:in `render'
        17: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:150:in `render_segment'
        16: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        15: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:158:in `block in render_segment'
        14: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:158:in `each'
        13: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:160:in `block (2 levels) in render_segment'
        12: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
        11: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        10: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
         9: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
         8: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
         7: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
         6: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
         5: from /var/lib/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
         4: from /var/lib/gems/2.7.0/gems/jekyll-exif-data-0.0.3/lib/jekyll/exif-data.rb:9:in `exif'
         3: from /var/lib/gems/2.7.0/gems/jekyll-exif-data-0.0.3/lib/jekyll/exif-data.rb:9:in `new'
         2: from /var/lib/gems/2.7.0/gems/exifr-1.3.9/lib/exifr/jpeg.rb:34:in `initialize'
         1: from /var/lib/gems/2.7.0/gems/exifr-1.3.9/lib/exifr/jpeg.rb:34:in `open'
/var/lib/gems/2.7.0/gems/exifr-1.3.9/lib/exifr/jpeg.rb:34:in `initialize': No such file or directory @ rb_sysopen - photos/original/DSC03516.JPG (Errno::ENOENT)

ruby -v                                   [21/08/23|14:27:25]
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by mk-mi-berlin** [comment]
Hi Andreas,

I updated to ruby-3.0.2, rebuild eventmachine with OpenSSL1.1 (to be compatible on BigSur) and still get that error:

bundle exec jekyll serve --trace
Configuration file: /Users/klein/git/photo-stream/_config.yml
            Source: /Users/klein/git/photo-stream
       Destination: /Users/klein/git/photo-stream/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: No such file or directory @ rb_sysopen - photos/original/IMG_9497.jpeg in feed.xml
/Users/klein/.rvm/gems/ruby-3.0.2/gems/exifr-1.3.9/lib/exifr/jpeg.rb:34:in `initialize': No such file or directory @ rb_sysopen - photos/original/IMG_9497.jpeg (Errno::ENOENT)

Maybe you or someone else has an idea?

Cheers, great project,
Matthias

**Comment by jessecrouch** [comment]
Hi I upgraded to Ruby 3, but I get the same result. Any ideas?

➜  ~/docs/clients/photography/photo-stream git:(master) ruby -v                                     [21/08/27|17:48:15]
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
➜  ~/docs/clients/photography/photo-stream git:(master) bundle exec jekyll serve                     [21/08/30|2:49:51]
Configuration file: /home/jesse/docs/clients/photography/photo-stream/_config.yml
            Source: /home/jesse/docs/clients/photography/photo-stream
       Destination: /home/jesse/docs/clients/photography/photo-stream/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: No such file or directory @ rb_sysopen - photos/original/DSC07969-1.jpg in feed.xml
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/home/jesse/.rvm/gems/ruby-3.0.0/gems/exifr-1.3.9/lib/exifr/jpeg.rb:34:in `initialize': No such file or directory @ rb_sysopen - photos/original/DSC07969-1.jpg (Errno::ENOENT)
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/exifr-1.3.9/lib/exifr/jpeg.rb:34:in `open'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/exifr-1.3.9/lib/exifr/jpeg.rb:34:in `initialize'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-exif-data-0.0.3/lib/jekyll/exif-data.rb:9:in `new'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-exif-data-0.0.3/lib/jekyll/exif-data.rb:9:in `exif'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:160:in `block (2 levels) in render_segment'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:158:in `each'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:158:in `block in render_segment'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:150:in `render_segment'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:79:in `render'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:131:in `render_liquid'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:80:in `render_document'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:539:in `block in render_pages'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `each'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `render_pages'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:211:in `render'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /home/jesse/.rvm/gems/ruby-3.0.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
        from /home/jesse/.rvm/gems/ruby-3.0.0/bin/jekyll:23:in `load'
        from /home/jesse/.rvm/gems/ruby-3.0.0/bin/jekyll:23:in `<main>'
        from /home/jesse/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
        from /home/jesse/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'

**Comment by waschinski** [comment]
Okay, what are the file/folder permissions? Maybe the Code really can't access the file. 

In addition you could try updating your gems which should be a simple `gem update`.

**Comment by fxjkhr** [comment]
had this problem, the pictures need to be placed in "photos/original", NOT "photos/original**s**"

the readme has the wrong info https://github.com/waschinski/photo-stream/blob/master/README.md#how-to-use

**Comment by waschinski** [comment]
> had this problem, the pictures need to be placed in "photos/original", NOT "photos/original**s**"
> 
> 
> 
> the readme has the wrong info https://github.com/waschinski/photo-stream/blob/master/README.md#how-to-use

Sharp eyes you got there - thanks for pointing that out! I will make sure to fix the reader ASAP!

**Comment by jessecrouch** [comment]
thank you so much!!

**Comment by waschinski** [comment]
Glad to hear it's working now.
